/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stocks;

import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author toshiba
 */
public class Stock extends javax.swing.JFrame {
    
    double [] product = new double[10];

    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jcmDiscount = new javax.swing.JComboBox();
        jbtnTotal = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jlblSubTotal = new javax.swing.JTextField();
        jlblTotal = new javax.swing.JTextField();
        jlblTax = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jcmVAT = new javax.swing.JComboBox();
        jcmAccType = new javax.swing.JComboBox();
        jcmPayMethod = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcmOrderID = new javax.swing.JComboBox();
        jcmCustomerID = new javax.swing.JComboBox();
        jtextFirstName = new javax.swing.JTextField();
        jtextSurName = new javax.swing.JTextField();
        jlblItemOrder = new javax.swing.JTextField();
        jlblNoofItem = new javax.swing.JTextField();
        jlblDateOrder = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextAddress = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jcmOnSales = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jcmProductID = new javax.swing.JComboBox();
        jlblProductName = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jlblDescription = new javax.swing.JTextField();
        jlblStockLevel = new javax.swing.JTextField();
        jlblReorderLevel = new javax.swing.JTextField();
        jlblOutofStock = new javax.swing.JTextField();
        jtextNoofOrder = new javax.swing.JTextField();
        jlblCost = new javax.swing.JTextField();
        jlblReorderDate = new javax.swing.JTextField();
        jlblAction = new javax.swing.JTextField();
        jlblRemainder = new javax.swing.JTextField();
        jlblExpires = new javax.swing.JTextField();
        jlblValid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("Tax");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("Discount");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setText("Total");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setText("Sub Total");

        jcmDiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmDiscount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "5", "10", "15", "20", "25" }));
        jcmDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmDiscountActionPerformed(evt);
            }
        });

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Rest");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jlblSubTotal.setEditable(false);
        jlblSubTotal.setBackground(new java.awt.Color(204, 204, 204));
        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblTotal.setEditable(false);
        jlblTotal.setBackground(new java.awt.Color(204, 204, 204));
        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblTax.setEditable(false);
        jlblTax.setBackground(new java.awt.Color(204, 204, 204));
        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblTaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(jcmDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jcmDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTotal)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("VAT");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Acc. Type");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Pay. Method");

        jcmVAT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmVAT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No", "Over 65" }));

        jcmAccType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmAccType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Credit Acct", "Debit Acct", "Customer Acct", "Comm Acct" }));

        jcmPayMethod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmPayMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Master Card", "Visa Card", "Debit Card" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcmAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmPayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jcmVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jcmAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jcmPayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Customer ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("FirstName");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Order ID");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("SurName");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Date Order");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Item Order");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Address");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("No. of Item");

        jcmOrderID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmOrderID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Ord ID", "ORDID09011", "ORDID09012", "ORDID09013", "ORDID09014", "ORDID09015" }));
        jcmOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmOrderIDActionPerformed(evt);
            }
        });

        jcmCustomerID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmCustomerID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Cus ID", "CID120701", "CID120702", "CID120703", "CID120704", "CID120705" }));

        jtextFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtextSurName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtextSurName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextSurNameActionPerformed(evt);
            }
        });

        jlblItemOrder.setEditable(false);
        jlblItemOrder.setBackground(new java.awt.Color(204, 204, 204));
        jlblItemOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblNoofItem.setEditable(false);
        jlblNoofItem.setBackground(new java.awt.Color(204, 204, 204));
        jlblNoofItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblDateOrder.setEditable(false);
        jlblDateOrder.setBackground(new java.awt.Color(204, 204, 204));
        jlblDateOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtextAddress.setColumns(20);
        jtextAddress.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jtextAddress.setRows(5);
        jScrollPane1.setViewportView(jtextAddress);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtextSurName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcmOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcmCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(160, 160, 160)
                                .addComponent(jlblNoofItem, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(162, 162, 162)
                                .addComponent(jlblItemOrder))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(163, 163, 163)
                                .addComponent(jlblDateOrder))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jlblDateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jlblItemOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblNoofItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(218, 218, 218))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcmOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jcmCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jtextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtextSurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Valid Form");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Remainder");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("On Sales");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Date Expires ");

        jcmOnSales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmOnSales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "On Sales", "Not On Sales" }));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Product Name");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Out of Stock");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Reorder Level");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Product ID");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Action");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("No. of Order");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Description");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Stock Level");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Cost");

        jcmProductID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmProductID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Product ID", "PID036501", "PID036502", "PID036503", "PID036504", "PID036505" }));
        jcmProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmProductIDActionPerformed(evt);
            }
        });

        jlblProductName.setEditable(false);
        jlblProductName.setBackground(new java.awt.Color(204, 204, 204));
        jlblProductName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblProductNameActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setText("Reorder Date");

        jlblDescription.setEditable(false);
        jlblDescription.setBackground(new java.awt.Color(204, 204, 204));
        jlblDescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblDescriptionActionPerformed(evt);
            }
        });

        jlblStockLevel.setEditable(false);
        jlblStockLevel.setBackground(new java.awt.Color(204, 204, 204));
        jlblStockLevel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblStockLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblStockLevelActionPerformed(evt);
            }
        });

        jlblReorderLevel.setEditable(false);
        jlblReorderLevel.setBackground(new java.awt.Color(204, 204, 204));
        jlblReorderLevel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblReorderLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblReorderLevelActionPerformed(evt);
            }
        });

        jlblOutofStock.setEditable(false);
        jlblOutofStock.setBackground(new java.awt.Color(204, 204, 204));
        jlblOutofStock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblOutofStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblOutofStockActionPerformed(evt);
            }
        });

        jtextNoofOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtextNoofOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNoofOrderActionPerformed(evt);
            }
        });

        jlblCost.setEditable(false);
        jlblCost.setBackground(new java.awt.Color(204, 204, 204));
        jlblCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblCostActionPerformed(evt);
            }
        });

        jlblReorderDate.setEditable(false);
        jlblReorderDate.setBackground(new java.awt.Color(204, 204, 204));
        jlblReorderDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblReorderDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblReorderDateActionPerformed(evt);
            }
        });

        jlblAction.setEditable(false);
        jlblAction.setBackground(new java.awt.Color(204, 204, 204));
        jlblAction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblActionActionPerformed(evt);
            }
        });

        jlblRemainder.setEditable(false);
        jlblRemainder.setBackground(new java.awt.Color(204, 204, 204));
        jlblRemainder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblRemainder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblRemainderActionPerformed(evt);
            }
        });

        jlblExpires.setEditable(false);
        jlblExpires.setBackground(new java.awt.Color(204, 204, 204));
        jlblExpires.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblExpires.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblExpiresActionPerformed(evt);
            }
        });

        jlblValid.setEditable(false);
        jlblValid.setBackground(new java.awt.Color(204, 204, 204));
        jlblValid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblValidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(175, 175, 175))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel46))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcmProductID, 0, 187, Short.MAX_VALUE)
                                    .addComponent(jlblProductName)
                                    .addComponent(jlblDescription)
                                    .addComponent(jlblStockLevel)
                                    .addComponent(jlblReorderLevel)
                                    .addComponent(jlblOutofStock)
                                    .addComponent(jtextNoofOrder)
                                    .addComponent(jlblCost)
                                    .addComponent(jlblReorderDate)
                                    .addComponent(jlblAction))
                                .addGap(74, 74, 74)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblValid, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblRemainder, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlblExpires)
                                    .addComponent(jcmOnSales, 0, 166, Short.MAX_VALUE))
                                .addGap(54, 54, 54))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel25)
                            .addComponent(jcmProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jlblValid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblExpires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                    .addComponent(jLabel22)
                                                                                    .addComponent(jlblProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel28))
                                                                            .addComponent(jlblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabel29))
                                                                    .addComponent(jlblStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel24))
                                                            .addComponent(jlblReorderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel23))
                                                    .addComponent(jlblOutofStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel27))
                                            .addComponent(jtextNoofOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel30))
                                    .addComponent(jlblCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel46))
                            .addComponent(jlblReorderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jlblAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jlblRemainder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jcmOnSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1730, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlblValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblValidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblValidActionPerformed

    private void jlblExpiresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblExpiresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblExpiresActionPerformed

    private void jlblRemainderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblRemainderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblRemainderActionPerformed

    private void jtextNoofOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNoofOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNoofOrderActionPerformed

    private void jtextSurNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextSurNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextSurNameActionPerformed

    private void jcmOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmOrderIDActionPerformed

    private void jlblTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblTaxActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jlblSubTotal.setText(null);
        jlblTax.setText(null);
        jlblTotal.setText(null);
        jlblCost.setText(null);
        jlblProductName.setText(null);
        jlblDescription.setText(null);
        jlblStockLevel.setText(null);
        jlblReorderLevel.setText(null);
        jlblOutofStock.setText(null);
        jtextNoofOrder.setText(null);
        jlblReorderDate.setText(null);
        jlblAction.setText(null);
        jtextAddress.setText(null);
        jtextSurName.setText(null);
        jtextFirstName.setText(null);
        jlblValid.setText(null);
        jlblRemainder.setText(null);
        jlblExpires.setText(null);
        jlblNoofItem.setText(null);
        jlblDateOrder.setText(null);
        jlblItemOrder.setText(null);
        jcmDiscount.setSelectedItem("0");
        jcmProductID.setSelectedItem("Select Product ID");
        jcmVAT.setSelectedItem("yes");
        jcmAccType.setSelectedItem("Credit Acct");
        jcmPayMethod.setSelectedItem("Cash");
        jcmOnSales.setSelectedItem("On Sales");
        jcmOrderID.setSelectedItem("Select Ord ID");
        jcmCustomerID.setSelectedItem("Select Cus ID");
        
        
        
        
        
        
        

    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
        double iTax, iDiscount;
        product[0]=Double.parseDouble(jtextNoofOrder.getText());
        product[1]=Double.parseDouble(jlblStockLevel.getText());
        
        double cTotal1 = (product[1] - product[0]);
        String CostD = String.valueOf(cTotal1);
        jlblRemainder.setText(CostD);
        //================================Add Up Total=================================================
        
        Object selectedItem = jcmDiscount.getSelectedItem();
        iDiscount = Double.parseDouble(selectedItem.toString());
        
        product[2]=Double.parseDouble(jtextNoofOrder.getText());
        product[3]=Double.parseDouble(jlblCost.getText());
        iDiscount = ((product[2] * product[3]) * iDiscount)/100;
        product[4] = ((product[2] * product[3])) - iDiscount;
        String SubTotalCost = String.valueOf(product[4]);
        jlblSubTotal.setText(SubTotalCost);
        
        product[5] = ((product[4]) * 7.5)/100;
        String ItemTax = String.valueOf(product[5]);
        jlblTax.setText(ItemTax);
        
        product[6] = product[4] + product[5];
        String TotalCost = String.valueOf(product[6]);
        jlblTotal.setText(TotalCost);
        
        product [7] = Double.parseDouble(jlblTax.getText());
        String Taxtodlr = String.format("$ % .2f", product[7]);
        jlblTax.setText(Taxtodlr);
        
        product [8] = Double.parseDouble(jlblSubTotal.getText());
        String SubTotaltodlr = String.format("$ % .2f", product[8]);
        jlblSubTotal.setText(SubTotaltodlr);
        
        product [9] = Double.parseDouble(jlblTotal.getText());
        String Totaltodlr = String.format("$ % .2f", product[9]);
        jlblTotal.setText(Totaltodlr);
        
        jlblNoofItem.setText(jtextNoofOrder.getText());
        
        
        
        
        
        
        //=============================================================================================
        if(cTotal1<5)
        {
            jlblAction.setText("Order More Product");
            Calendar timer = Calendar.getInstance();
            timer.getTime();
            SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-YYYY");
            jlblDateOrder.setText(Tdate.format(timer.getTime()));
            jlblReorderDate.setText(Tdate.format(timer.getTime()));
            jlblValid.setText(Tdate.format(timer.getTime()));
            jlblExpires.setText(Tdate.format(timer.getTime()));
            
            
        }
        else
        {  jlblAction.setText("No Order Requested");
            Calendar timer = Calendar.getInstance();
            timer.getTime();
            SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-YYYY");
            jlblDateOrder.setText(Tdate.format(timer.getTime()));
            jlblReorderDate.setText(Tdate.format(timer.getTime()));
            jlblValid.setText(Tdate.format(timer.getTime()));
           jlblExpires.setText("Item Valid");
    }  
            
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jlblActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblActionActionPerformed

    private void jlblReorderDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblReorderDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblReorderDateActionPerformed

    private void jlblCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblCostActionPerformed

    private void jlblOutofStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblOutofStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblOutofStockActionPerformed

    private void jlblReorderLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblReorderLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblReorderLevelActionPerformed

    private void jlblStockLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblStockLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblStockLevelActionPerformed

    private void jlblDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblDescriptionActionPerformed

    private void jlblProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblProductNameActionPerformed

    private void jcmProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmProductIDActionPerformed
        // TODO add your handling code here:
        if(jcmProductID.getSelectedItem().equals("PID036501"))
        {
        jlblProductName.setText("Rice");
        jlblItemOrder.setText("Rice");
        jlblDescription.setText("White grain");
        jlblStockLevel.setText("200");
        jlblReorderLevel.setText("30");
        jlblOutofStock.setText("5");
        jlblCost.setText("12.8");
        
        
        }
        
        if(jcmProductID.getSelectedItem().equals("PID036502"))
        {
        jlblProductName.setText("Beans");
        jlblItemOrder.setText("Beans");
        jlblDescription.setText("White/Black grain");
        jlblStockLevel.setText("320");
        jlblReorderLevel.setText("50");
        jlblOutofStock.setText("10");
        jlblCost.setText("10.5");
        
        }
        
        if(jcmProductID.getSelectedItem().equals("PID036503"))
        {
        jlblProductName.setText("Carrot");
        jlblItemOrder.setText("Carrot");
        jlblDescription.setText("Vegetable");
        jlblStockLevel.setText("200");
        jlblReorderLevel.setText("10");
        jlblOutofStock.setText("2");
        jlblCost.setText("1.8");
        
        }
        
        if(jcmProductID.getSelectedItem().equals("PID036504"))
        {
        jlblProductName.setText("Bread");
        jlblItemOrder.setText("Bread");
        jlblDescription.setText("White grain");
        jlblStockLevel.setText("150");
        jlblReorderLevel.setText("20");
        jlblOutofStock.setText("5");
        jlblCost.setText("1.48");
        
        }
        
        if(jcmProductID.getSelectedItem().equals("PID036505"))
        {
        jlblProductName.setText("Eggs");
        jlblItemOrder.setText("Eggs");
        jlblDescription.setText("Poultry");
        jlblStockLevel.setText("300");
        jlblReorderLevel.setText("40");
        jlblOutofStock.setText("5");
        jlblCost.setText("1.34");
        
        }
    }//GEN-LAST:event_jcmProductIDActionPerformed

    private void jcmDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmDiscountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JComboBox jcmAccType;
    private javax.swing.JComboBox jcmCustomerID;
    private javax.swing.JComboBox jcmDiscount;
    private javax.swing.JComboBox jcmOnSales;
    private javax.swing.JComboBox jcmOrderID;
    private javax.swing.JComboBox jcmPayMethod;
    private javax.swing.JComboBox jcmProductID;
    private javax.swing.JComboBox jcmVAT;
    private javax.swing.JTextField jlblAction;
    private javax.swing.JTextField jlblCost;
    private javax.swing.JTextField jlblDateOrder;
    private javax.swing.JTextField jlblDescription;
    private javax.swing.JTextField jlblExpires;
    private javax.swing.JTextField jlblItemOrder;
    private javax.swing.JTextField jlblNoofItem;
    private javax.swing.JTextField jlblOutofStock;
    private javax.swing.JTextField jlblProductName;
    private javax.swing.JTextField jlblRemainder;
    private javax.swing.JTextField jlblReorderDate;
    private javax.swing.JTextField jlblReorderLevel;
    private javax.swing.JTextField jlblStockLevel;
    private javax.swing.JTextField jlblSubTotal;
    private javax.swing.JTextField jlblTax;
    private javax.swing.JTextField jlblTotal;
    private javax.swing.JTextField jlblValid;
    private javax.swing.JTextArea jtextAddress;
    private javax.swing.JTextField jtextFirstName;
    private javax.swing.JTextField jtextNoofOrder;
    private javax.swing.JTextField jtextSurName;
    // End of variables declaration//GEN-END:variables
}
